### PR TITLE
Add dotnet

### PR DESCRIPTION
**Pull request by Azer0s**
Thanks for the project! Used it to clean up a bunch of old C# and JS projects. Am a bit unsure how to add the tests for dotnet tho. Hope this contribution is useful.

### CODE REVIEW

**Comment by kevinbader** [comment]
Thanks for the contribution! Some observations:

- The probe is always given the directory, so checking for extension is useless. I've only just noticed that the docs for probe in the trait don't say anything about that, unfortunately.
- `BuildToolManager::new` should not register any probes, see https://github.com/kevinbader/makeclean/blob/main/src/build_tool_manager.rs#L31
- I've recently refactored a bit and added some helpers to make common stuff simpler; see https://github.com/kevinbader/makeclean/blob/main/src/build_tools/mix.rs#L42 for an example.
- For testing this, see https://github.com/kevinbader/makeclean/blob/main/tests/tests/build_tools.rs#L26, where you could add a corresponding dotnet_init function in a similar fashion. I see you've added a module at tests/util/mod.rs, but the module itself is missing from the commit.

**Comment by Azer0s** [comment]
Will change point 2-4 as soon as I find the time 😄 
But regarding the first point: I always get files as well.

image

image

**Comment by kevinbader** [comment]
> But regarding the first point: I always get files as well, which is why I check for file extension. Noticed that the first time I ran the tool and thought it was intentional.

Indeed! Thanks for pointing that out, that was not intended. Instead, the `BuildToolProbe`s should only check directories and not individual files. I've fixed and hopefully cleared that up in 07db099f500a5ee88d2e3ebeceb52ca74b2c20a7

**Comment by kevinbader** [comment]
This has become quite stale I'm afraid. I'm not using dotnet myself, so I'll close this for now. Feel free to re-open if you'd like to bring this up-to-date - writing probes has become a bit easier since then.

**Pull request closed without merging**
